vim/vscode-code-actions.vim
It's quite frequent usecases to use mousehover to see compiler error messages / or other information provided like below:
This PR attempts to mimic vscodevim's keybinding, bringing `gh` to server as mouse hover in vscode.
Honestly not sure if this is desired changes (and as vim beginner unsure if there's predefined bindings), open to suggestions.
p.s: bumd q, is it possible user can configure this actions by own instead of upstream?
=> feat(actions): bind gh to mousehover

package.json
- relates to #71 
This PR bumps up neovim client includes msgpack dependency update.
=> build(package): bump up neovim to latest

src/controller.ts, src/test/suite/dot-repeat.test.ts, src/utils.ts, vim/vscode-options.vim
This one is better than PR in #160 
This is utilizing the fact that `.` command repeats last stuff globally across all buffers & windows. So we tricking neovim by creating separate window & buffer and replaying last subsequent changes here by using `nvim_input` after exiting insert mode. After that this temporary buffer is being destroyed
Fixes #76
=> Workaround dot-repeat by replaying last changes in separate buffer

package.json, src/extension.ts, src/utils.ts
Fixes #137 
This branch adds operating system specific paths (neovimPath). ~I still need to add some tests~ and actually manually check if it even works.
Anyways, I'm working on it. Uploading a draft PR as a heads up
- Create settings and logic for overriding settings on Windows, Linux and OSX:
neovimPath and neovimInitPath logic is written here in such a way that if neovimPath exists, the system specific settings are ignored. So people who are oblivous to the deprecation of neovimPath won't have a broken workflow when this is merged.
=> is137 Add settings for operating system specific paths

vim/vscode-code-actions.vim, vim/vscode-file-commands.vim, vim/vscode-insert.vim, vim/vscode-tab-commands.vim, vim/vscode-window-commands.vim
Vimscript uses settings-dependent case comparsion by default. Use case-sensetive comparsion to avoid issues caused by `set ignorecase`. Closes #308.
=> Use case-sensetive comparsion

README.md
In reference to https://github.com/asvetliakov/vscode-neovim/issues/290
=> Escape keys should only work in editorTextFocus mode

src/controller.ts, src/test/suite/insert-mode.test.ts
1. Rebind type command early before sending changes to neovim
2. Store any pressed keys here
3. Send them with escape command
fixes #324
=> Store additional keystrokes to pending key queue

src/command_line.ts
When in command line mode, pressing up and down to go through history
would lag enough to make it annoying when pressing up or down multiple
times quickly. Calling show() on the QuickPick after setting the new value
fixes this.
=> Fix lag when cycling through command history

src/controller.ts
Exec `wslpath` to resolve the extension's path before executing neovim.
Let's be shell agnostic, so users who default to fish or other quirky shells can use this extension too.
Fixes #147
=> Fix shell-dependent logic in WSL

package.json, src/buffer_manager.ts, src/extension.ts, src/main_controller.ts
Fixes #340 
`ui_attach` should be called after we bind request event handler. Otherwise neovim can request `VSCodeCall/VSCodeExtensionCall` before and stuck forever waiting for a response
Also make non-debounced version of sync layout methods and wait for them before completing `init()`
=> Fix possible deadlock

README.md, vim/vscode-code-actions.vim
Having both gd and gf mapped to "revealDefinition" seemed redundant, so this PR maps gf to "revealDeclaration". In some languages like C++ this makes a difference, and the mnemonic "go to forward declaration" makes sense for gf. gd remains "go to definition".
I refactored the `vscodeGoToDefinition` function to support these two modes without needing to duplicate the function.
I also provided a binding for "revealReferences", and since "hover" is gh, I figured gH is a decent choice.
Finally, I'm not sure why `<C-w>gF` was mapped to the same thing as `<C-w>gf`, I know it was meant to mirror neovim but there are so many other missing keybindings that I don't think this little one is worth the space it takes.
With neovim now working inside peek, this functionality has suddenly become …
=> Improve code actions

package.json, src/commands_controller.ts, src/extension.ts, src/main_controller.ts
https://stackoverflow.com/questions/49997089/vscode-how-to-set-that-when-i-press-ctrl-up-or-down-arrow-the-cursor-move-wi
Vs Code, by default, doesn't update cursor position after scrolling, which is not the case in vim. This pr makes experience more similar to scrolling in vim.
=> fix: cursor is left behind

vim/vscode-window-commands.vim
I was wondering why `<C-w><C-w>` wasn't working in the extension and stumpled upon these duplicate definitions for `<C-w>w` & `<C-w><C-w>` for the same modes respectively.
This PR changes the definitions such that `<C-w>w` and `<C-w><C-w>` work in both normal and visual modes.
=> fix <C-w>w & <C-w><C-w>

README.md, vim/vscode-code-actions.vim
Currently When you type `<C-w>gf`, it does not work because `editor.action. revealDeclarationAside ` does not exist in vscode.
=> Remove <C-w>gf command

README.md, vim/vscode-code-actions.vim, vim/vscode-file-commands.vim, vim/vscode-insert.vim, vim/vscode-jumplist.vim, vim/vscode-neovim.vim, vim/vscode-options.vim, vim/vscode-scrolling.vim, vim/vscode-tab-commands.vim, vim/vscode-window-commands.vim
I believe this was suggested by @Shatur95 in another issue.
A command exists called `<Cmd>` that replaces the need for `:<C-U>` and `gv` in mappings that call commands.
In brief: (`help :map-cmd`),
> The <Cmd> pseudokey begins a "command mapping", which executes the command
directly (without changing modes).
This is more flexible than `:<C-U>` in visual and operator-pending mode, or
`<C-O>:` in insert-mode, because the commands are executed directly in the
current mode (instead of always going to normal-mode).  Visual-mode is
preserved, so tricks with |gv| are not needed.  Commands can be invoked
directly in cmdline-mode (which would otherwise require timer hacks).
I did a search and replace for this over the whole project, as well as removed all the unnecessary `gv` commands and even …
=> Refactor Vimscript

src/highlight_manager.ts, src/highlight_provider.ts
This deleted lines were causing to apply vim HL regardless if it should be ignored or not. Especially frustrating with `MatchParen` HL at end of the line
=> Remove unneeded HL optimization

.github/workflows/build_test.yml, .gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json, .vscodeignore, package.json, webpack.config.js, yarn.lock
There is `Critical dependency: the request of a dependency is an expression` error coming from `neovim` node client, but it's safe to ignore since it's related to neovim remote plugin loading, which is requiring global installed version anyway
Also fixes winston logger spam
Closes #134 
Relates https://github.com/neovim/node-client/pull/136#issuecomment-688453651
=> Webpack bundling

package.json, src/buffer_manager.ts, src/cursor_manager.ts, tsconfig.json, webpack.config.js, yarn.lock
This PR attempts to improve #377 by enablind tree shaking. 
To utilize proper tree shaking, PR replaces lodash to esm exports lodash (`lodash-es`) and updates ts-loader config to webpack properly analyze tree shaking imports. 
Size comparison of bundle looks like below:
Previous
After
Total bundle size went down from 415 -> 341, among those lodash now takes ~3KB only.
=> build(webpack): enable tree shaking

vim/vscode-file-commands.vim
I often use :x to quickly save and close a file, but I noticed it was not mapped and caused issues where the extensions stopped working when a another file was opened.
xa is already implemented, so this is just for the single file save/close
=> Map :x to Wq

src/extension.ts, src/main_controller.ts
Fixes #147 
I tested with bash and fish in VSCode 1.51.0
=> Launch nvim in WSL in a shell-agnostic way

src/main_controller.ts
When the first file is opened, set vim cwd to the
current workspace folder root if one is open
else the home directory of the user(determined by '~').
The workspace folder is not set properly before the first file is opened, so the neovim 'c' flag does not work and 'cmd' is used.
Since extensions are reloaded when a new workspace is opened, the correct directory is set even when a new workspace is opened.
This change will make 'vim-fugitive' work.
=> Set vim cwd as vscode workspace

src/test/suite/insert-mode.test.ts, vim/vscode-neovim.vim
With this change using Ctrl-A in insert mode will take into account the column position as well. This means that only the newest insert gets pasted.
closes #283
=> Use column position when using Ctrl-A in insert

.github/workflows/build_test.yml, README.md, vim/vscode-window-commands.vim
NOTE Breaking change.
* Implement `manageEditorHeight` and `manageEditorWidth` based on `help CTRL-W`
| Tag | Command  | Action in normal mode |
| ----------- | ----------- | ----------- | 
| CTRL-W_+ |	CTRL-W +	|   increase current window height N lines |
| CTRL-W_- |	CTRL-W -	|   decrease current window height N lines |
| CTRL-W_> |	CTRL-W >	|   increase current window width N columns |
| CTRL-W_< |	CTRL-W <	|   decrease current window width N columns |
* Keeping `manageEditorSize` and its keybindings commented-out as backup. This command increases/decreases both height & width of the active editor while also decreases/increases other windows (e.g. panel) all at the same time. To restore previous functionality of VSCode command 'Increase/decrease current view size': …
=> Implement manageEditorHeight and manageEditorWidth

README.md
Upon using the `vscode-neovim.neovimPath` command in settings.json, you get a warning saying that the command has been deprecated and that you should utilize `vscode-neovim.neovimExecutablePaths.win32/linux/darwin`.
It's just a small fix in the README at the end of the day.
=> Replace deprecated neovimPath command in README

src/extension.ts
Using the node.js variable process.platform the platform node is running on can be found. If it isn't windows based then the wsl setting is set to false. 
Manually tested on windows 10 and a debian based OS. 
closes #381
=> Ignore WSL option on non windows OS

src/commands_controller.ts, vim/vscode-scrolling.vim
* Fix H M L keys first moving to first character of the line before it's triggered. Closes https://github.com/asvetliakov/vscode-neovim/issues/367
* Internally, H M L keys uses native VSCode commands, which don't register jumplist. Fix by registering jumplist in Vim e.g. for subsequent use of `<C-o>`
If you look at commit messages https://github.com/asvetliakov/vscode-neovim/commit/e67f5203ed8ec0bb958982a06c464e6758f4d54e, initially I added hacky fixes
```ts
case "move-cursor": {
const [to] = args as ["top" | "middle" | "bottom"];
// Fix bug: `goToLine` First moving to first character of the line before `goToLine` is triggered.
// Temporary solution: Move cursor to first character of the line and delay by 5 milliseconds before triggering `goToLine`. 1 millisecond delay failed manual …
```
=> H M L keys: Fix bugs, add jumplists.

src/commands_controller.ts, vim/vscode-motion.vim, vim/vscode-neovim.vim
Add `g0` and `g$` for normal mode. (Partially?) Closes https://github.com/asvetliakov/vscode-neovim/issues/433
For other modes e.g. `vg0` `cg0`, they are not as straightforward due to e.g. 
* visual mode not producing the real VSCode selection
* delay between VSCode command and Vim command
I tried adding `vg0` `vg$`, playing around a bit but gave up. Kinda buggy. Might revisit in future. `g0` and `g$` covers some use cases for now.
Start/end of screen line motion in normal mode
`g0`
`g$`
<br>
=> Add g0 g$ for normal mode

src/cursor_manager.ts, src/test/suite/visual-modes.test.ts
related to #477 . This probably will lead to some consequences for go-to-def/outline navigation and other code jumps - they won't be centered anymore.
=> Exploration - Try default revealing

src/highlight_provider.ts
If the foreground or background colour keys are not specified, the plugin forcefully sets the colours to be the theme's default foreground/background colours. This means that if the text colour was changed by syntax hl, then it would become white. 
This is useful for underlining something without changing the colour - notably for use with `quick-scope` or `vim-current-word`:
```vim
highlight QuickScopePrimary guifg=NONE guisp='#afff5f' gui=underline ctermfg=NONE cterm=underline
highlight QuickScopeSecondary guifg=NONE guisp='#5fffff' gui=underline ctermfg=NONE cterm=underline
```
Hopefully this does not cause any problems! I'm lucky to have figured this out :slightly_smiling_face: 
Do you think the above snippet should be added to the readme?
Finally, do you think the default underline …
=> Refactor hl attrs to not override default colors

src/main_controller.ts
Wrap `${extensionPath}` in single quotes to alleviate issues with spaces existing in `extensionPath` var.
=> Closes #509

vim/vscode-window-commands.vim
with vim, you could execute window commands without letting go of
of the ctrl key which is much more convenient and fluid than having
to let go with your pinky.
=> add <c-w><c-v>, <c-w><c-s>, and <c-w><c-o> commands

.prettierrc.js, README.md, package.json, vim/vscode-code-actions.vim, vim/vscode-jumplist.vim
This is my work in progress for refactoring keybindings and readme. I hope you agree with the changes, and I will explain some of the keybindings at a later time. For now, I just want to show my progress, and see if you have any suggestions or feedback.
Would it be better to split this into two PRs? I put them in one because the readme needs to be changed to reflect the keybindings anyways.
**Todo:**
=> Refactor bindings and README

package.json
Fixes #388, now you can paste from the search register in insert mode with `<C-r>`.
=> Fix search register paste in insert mode (#388)

package.json
Fixes #262. The user still needs to manually install neovim on the remote machine, but then this plugin should be able to work in the browser.
=> Add workspace to `extensionKind` (#262)

README.md
[Neovim 0.5.0](https://github.com/neovim/neovim/releases/tag/v0.5.0) is no longer a nightly build, so this PR updates the README to remove the nightly references.
=> Remove the Neovim 0.5.0 nightly references from the README

README.md, package.json, vim/vscode-code-actions.vim
I hope to solve some of the issues I have introduced and improve the vscode bindings file.
Background info: 
- keybindings are evaluated bottom to top
- the first keybinding that matches the key and when clause is selected
- `&&` has more priority than `||` in when clause, ex. `a || b && c` == `a || (b && c)`
The way the new escape bindings work are:
- in insert mode or visual mode, escape will *always* return to normal mode
- in normal mode, if certain vscode elements are open, escape will close them. If not, it will send to neovim
Situations where escape is sent to vscode **only in normal mode**: `markersNavigationVisible, parameterHintsVisible, inReferenceSearchEditor, referenceSearchVisible, dirtyDiffVisible, notebookCellFocused`
`inReferenceSearchEditor && neovim.mode == normal || …
=> Refactor package.json bindings 

src/status_line_manager.ts
Solves #270.
It seems like there is a tiny buffer in the communication channel between neovim and vscode. As a result, there might be multiple `msg_showmode` messages a singular neovim notification (as seen in the screenshot below). This issue is likely to occur when there is an edit during the insert mode as neovim would issue several `msg_showmode` messages. However, current implementation only uses the first notification, which is the stale data indicating the mode string should still be `-- INSERT --`. This PR fixes this issue by using the latest message instead of the old one.
=> Fix jk not removing "--INSERT--"

.vscode/tasks.json, src/main_controller.ts
It looks like #334 accidentally ignored `vscode-neovim.mouseSelectionStartVisualMode`.
Explained here: https://github.com/asvetliakov/vscode-neovim/issues/395#issuecomment-897005222
This PR re-enables that setting.
=> Fix vscode-neovim.mouseSelectionStartVisualMode

src/buffer_manager.ts
Fixes #675
Open commands (:e, :split, :vsplit, .etc) do not open workspace files.
This is because it tries to open the file with just the filename, but the path is also needed when opening documents in vscode.
Resolve the workspace root folder path with the input path to get the files absolute path before opening.
This fix also works for relative and absolute paths to files outside the workspace.
=> Fix command line open workspace files

.github/workflows/build_test.yml
The _create_ job in the _build_test.yml_ workflow: fails on the _Install VSCE_ step due to node version 14 requirement
Bumped node version from 12  to 14 in the workflow jobs
=> Bump workflow node version from 12 to 14

package.json
When the find widget or notification center is visible, pressing `Esc` should close them instead.
=> fix: improved `vscode-neovim.escape`'s when condition

src/multiline_messages_manager.ts
The vscode-neovim Output channel has some weird behavior:
1. It auto-closes when it loses focus.
2. It clears itself (e.g. on `:messages`) instead of just appending.
3. It doesn't log most Nvim messages.
This makes the Output channel not very useful except for one-off
invocations `:messages`.
1. Always append.
2. Only *show* the Output channel, don't move the cursor there.
3. Don't try to be clever about clearing the Output channel or
auto-hiding it.
- This allows the user to keep the Output channel open and see
results of sequential commands (like a REPL, as `:` is intended).
4. Print all messages (except `return_prompt`).
closes #880
ref #334
@asvetliakov any objections here?
=> feat(messages): show more messages in Output

src/test/suite/insert-mode.test.ts, vim/vscode-neovim.vim
Fixes #402 and solves #283.
Current implementation was correctly getting the boundaries for the inserted text, but it was removing the front text first, shifting the position of the remaining text and thus incorrectly removing the text coming after it.
By simply removing the tail first, the shift happens only after the inserted text has been trimmed, so it works correctly now.
And it needed to be substracted 2 instead to 1 for the tail range because of the `colEnd` position being actually +1 from the last letter of the inserted text and the array range getting until -1 of the specified end index. So the difference is actually 2.
=> Fix i_Ctrl-a

src/multiline_messages_manager.ts
Problem:
Nvim can produce multiline messages for common actions like search.
Solution:
Don't focus the Output view for fewer than 3 lines.
ref #881
ref https://github.com/vscode-neovim/vscode-neovim/pull/881#issuecomment-1124323231
=> feat(messages): show Output less frequently

src/document_change_manager.ts, src/test/suite/utils.test.ts, src/utils.ts
This is my attempt to fix #829. The idea is to use `fast-diff` (already in use by other parts of extension) to determine the minimum set of changes to a line required to sync back VS Code to Neovim (after a buffer event). This list of operations is then applied to the text builder object provided by `editor.edit()` (part of Code Extension API).
=> Improve efficiency applying small edits

src/command_line.ts
Command completion uses space to delimit and replace the current command with the incoming completion item.
This causes completion with paths & command symbols to be completely replaced with the incoming completion. (if space is not used)
Use path symbols and vim command symbols to delimit the current command, then compare the last delimited item with the incoming completion item.
Fixes #860
=> Fix command completion for path and command symbols

src/cursor_manager.ts
Solves #773 and partially addresses #573.
Somehow a sequence of cursorMove commands is causing a bug in vscode. Removing them and directly setting the cursor location solves this issue. We don't need cursorMove vscode commands in this case anyways as less than one line move does not seem to get registered in jumplist.
Since the extension is getting highlights from redraw notifications, which is limited by window size, and neovim did not make the starting column of the current viewport in buffer available in the drawing notifications, the visual mode still displays incorrectly in vscode. However, it seems like the actual editing itself is working properly. There is no good fix to this other than implementing the display part of visual mode in the extension.
=> Fix b on long lines

package.json, src/commands_controller.ts, src/document_change_manager.ts, src/test/suite/composite-escape.test.ts, src/test/suite/insert-mode-additions.test.ts, src/test/suite/insert-mode.test.ts, src/typing_manager.ts, vim/vscode-neovim.vim
Currently, two sets of insert mode bindings are used:
1. custom vscode bindings:
commands like `C-w`, `C-r`, `<C-o>` are connected to vscode commands. These differ from nvim functionality and add to code bloat.
2. macro recording passthrough bindings:
when a macro is being recorded, the plugin directly sends the commands to nvim. This then applies the actions.
The problem with only using the nvim bindings is that when you type in insert mode, and then try to use the nvim bindings, nvim is not aware of the text you just typed, causing issues.
Make a generic "sync-send" command for all insert-mode bindings that syncs changes and then allows nvim to handle the commands. This seems to work well for C-w and others. This also lets the ext handle C-r and others. 
~~The code in typing_manager was …
=> refactor(insert): remove custom insert mode bindings

src/buffer_manager.ts
This fixes a race condition that causes the extension to freeze in normal mode if someone changes tabs fast enough.
The race condition happens because the code in `syncLayout` doesn't handle the case where the visible editors and the active editor changes while `syncLayout` is still running correctly. In that case, while `syncLayout` is running due to the initial change, it will resolve `changeLayoutPromise` after the visible editors change. That causes `syncActiveEditor` to try to set the current window in Neovim, but will use the new active editor, so it will fail since that new editor wasn't in the list of visible editors when `syncLayout` was run, meaning that the Neovim window for that editor wasn't set up.
This PR:
- fixes the race condition by using a cancellation token to avoid …
=> Fix normal mode freezing after switching windows

package.json, src/viewport_manager.ts
Fixes #976 by removing some messages. This makes the logging behavior more consistent with that of `buffer_manager`, letting downstream applications handle errors. Reported issue on Grid 1 should not affect editing experience as it is not displayed ([Grid 1 is the global grid used by default for the entire editor screen state](https://neovim.io/doc/user/ui.html#ui-linegrid)).
=>  fix(viewport_manager): fix logging messages 

package.json, src/commands_controller.ts, src/document_change_manager.ts, src/extension.ts, src/main_controller.ts, src/test/suite/vscode-integartion-specific.test.ts, src/utils.ts, vim/vscode-scrolling.vim
Window scroll commands don't move the cursor and instead just scroll the window. This differs from nvim behavior. This is because the extension intercepts the keybindings and applies vscode commands instead. The solution from #528 and #855 simply improves the logic in the plugin to move the cursor. However, this adds complexity and increases the separation from nvim.
Remove all custom code for cursor scrolling and allow nvim to handle it itself. However, I have found two problems:
- due to `scrolloff=100`, the scrolling commands behave strangely, and don't reach the top of the screen. c-d scrolls twice as far as it should. However, this can't be avoided according to https://github.com/vscode-neovim/vscode-neovim/blob/52ff62612d3bb9ae2a50ce00b9e068c5d175abda/src/main_controller.ts#L55. …
=> fix(scrolling): fix c-u/c-y/c-f/c-b by deletion

src/typing_manager.ts
Reverts vscode-neovim/vscode-neovim#900
=> Revert "fix(typing_manager): Non-English input method can replace chars"

src/main_controller.ts
followup on https://github.com/vscode-neovim/vscode-neovim/pull/952
this just moves the arguments around so that --clean doesn't override the config passed by -u
=> fix: settings.clean no longer overides settings.customInitFile

README.md
Capitalized the "p" in the "Plugins" hyperlink relative reference so it takes the user to the Plugins Wiki page (https://github.com/vscode-neovim/vscode-neovim/wiki/Plugins) instead of "Page Not Found."
=> Doc: Fix link to "Plugins" wiki in `README.md`

README.md
`workbench.list.automaticKeyboardNavigation` no longer a valid setting in settings.json
=> Remove invalid vscode config setting from README.md

package-lock.json, package.json, src/cursor_manager.ts, src/document_change_manager.ts, src/typing_manager.ts, src/utils.ts
I started to work on fixing #543. 
Helps #84
So far it seems to work well, though a couple tests fail.
Unfortunately, it does not seem to fix either dot-repeat or marks. Marks are lost like before, and dot-repeat does not replay any of the changes sent using set_text.
I tried sending the changes to nvim in real-time, which showed promise. With this, when you type, it sends individual characters to nvim asynchronously (so no typing lag). However, this also didn't fix dot-repeat, and had cursor pos syncronization issues.
This does reduce code bloat however, and might improve performance (especially in the case where vscode makes changes in normal mode).
=> feat(document_change_manager): replace `nvim_buf_set_lines` with `nvim_buf_set_text`

src/buffer_manager.ts, src/main_controller.ts, src/mode_manager.ts, src/test/suite/vscode-integartion-specific.test.ts
This mirrors nvim functionality. This also fixes the issue where the cursor is not updated to the click position when switching tabs. 
Depends on https://github.com/vscode-neovim/vscode-neovim/pull/992. 
Closes #716, fixes https://github.com/vscode-neovim/vscode-neovim/issues/613, fixes #776.
If you want to keep existing behaviour, use `au BufEnter * stopinsert`.
Note: this only consists of the last commit.
=> feat(buffer_manager): don't exit insert mode when switching tabs

src/highlight_provider.ts
@theol0403  sorry I just realize It is not only search and incsearch group.
highlight group of that config can make the ext_mark overlay broken
https://github.com/vscode-neovim/vscode-neovim/blob/master/package.json#L234
=> fix(highlight): check overlay from config

README.md
It seems that the https://vsmarketplacebadge.apphb.com is down for a while, so I replace the marketplace badge with the one generated by https://shields.io.
Extra color `#4c1` and label `Visual Studio Marketplace` settings were added to make it looks like the original badge.
Screenshot source: https://web.archive.org/web/20220413024110/https://github.com/vscode-neovim/vscode-neovim
=> docs(readme): fix visual studio marketplace badge

package.json, src/extension.ts, src/main_controller.ts
https://github.com/neovim/neovim/pull/22128
Personally I want a separate neovim config just for vscode, which can be achieved by setting `$NVIM_APPNAME`
=> feat: add $NVIM_APPNAME option

src/buffer_manager.ts, src/highlight_manager.ts
`substr` is deprecated (was used for compatibility with Internet Explorer).
Replaces the two occurrences of `substr` with `substring`
=> update substr (deprecated) to substring

.gitignore
Adds `Session.vim` to `.gitignore` for those who make use of `mks!` in Neovim while editing this project. 
I think this is a reasonable PR, since we all are Vim users.
=> chore(gitignore): Session.vim

.github/dependabot.yml
This makes it easier to update deps.
Should I group all deps into one PR for less noise?
=> build(deps): add dependabot

vim/vscode-tab-commands.vim
Fixes #670
The fix uses VSCode workbench.action.openEditorAtIndex# where # stands for tab number.
It's normally used for CMD+# switching among tabs so I don't know if it works beyond 9, but even if limited to 9 it's more accurate than current behavior.
It's my first time contributing to this amazing project so pardon me if I did something wrong. Please let me know if there is anything else that I can do for this PR.
=> fix issue '{count}gt command not jumping to correct tab #670'

package.json, vim/vscode-jumplist.vim
C-t is used in vim as jumping back in tag stack. With LSP, this is
normally used for "navigating back". So adding this to vscode neovim for
the same convention.
However, as I tested, it does NOT currently work - it *can* send <c-t>
to neovim alright. But I got "E73: tag stack empty", as if c-t were
still bound to neovim's default c-t behavior (jump back in tag stack).
I expected it to have been mapped to `workbench.action.navigateBack`.
Any hint?
TEST:
```
npm install vsce
export PATH=`realpath node_modules/.bin`:$PATH
vsce package
code --install-extension vscode-neovim-0.0.83.vsix
```
=> Support <c-t> as navigateBack

package.json
Fixes #1297
Primary focus is to allow using `ctrl+w` to delete the last word. <s>Will introduce a new issue for now: We cannot escape the terminal (for now).</s>
=> fix: colliding ctrl+w bindings in terminal

src/main_controller.ts
Set the [`WSLENV`](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/) environment variable to pass `NVIM_APPNAME` into WSL.
See #1303 for more discussions.
Fixes #1295.
=> feat(main): set `WSLENV` to pass `NVIM_APPNAME` into WSL

src/mode_manager.ts, src/typing_manager.ts
This should close #1304; I've tried it out locally and everything seems to behave as expected. 🙂
(Force-pushed after linting.)
=> fix(mode): allow escaping from replace mode

package-lock.json, package.json, runtime/lua/vscode.lua, runtime/lua/vscode/defaults.lua, runtime/lua/vscode/force_options.lua, runtime/lua/vscode/highlight.lua, src/extension.ts, src/highlight_manager.ts, src/highlight_provider.ts, src/main_controller.ts, src/test/suite/dot-repeat.test.ts
This attempts to simplify the highlight manager and improve the mechanism for ignoring syntax groups.
Instead of providing vscode options to do this, it instead relies on neovim configuration to effectively erase the syntax groups. 
Ref: https://github.com/vscode-neovim/vscode-neovim/issues/1264
=> fact(highlight): ignore undesired highlights from vim side instead of vscode side

README.md, runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/api.lua, src/cursor_manager.ts, src/custom_commands_manager.ts, src/main_controller.ts, vim/vscode-code-actions.vim, vim/vscode-neovim.vim
Adds `VSCodeNotifyRange` but with a more concise and accurate impl. Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1355, fixes https://github.com/vscode-neovim/vscode-neovim/issues/1351, fixes https://github.com/vscode-neovim/vscode-neovim/issues/1345.
Also re-adds `VSCodeCommentary` and fixes a bug with `VSCodeNotify`.
=> fix(cursor): re-add new VSCodeNotifyRange impl

src/highlight_provider.ts
The bug was caused due to the new behavior in 0.4.0 that can now render blank highlights, used for eol visual cursor and blank leap.nvim labels. However, flash.nvim adds its grey overlay to every single cell in the buffer, and so thousands of "blank" cells were trying to be rendered using text decoration. This commit makes it so it will only render highlights that are over text.
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1369, fixes https://github.com/vscode-neovim/vscode-neovim/issues/1349
=> fix(highlight): remove flash.nvim lag

src/status_line.ts
Currentlly, we use `window.titleSeparator` as the separator. Of course, it is best to provide a separate configuration, whether in vscode or nvim. But the priority is not high.
Resolve: #1251
=> feat(statusline): combine status line items

src/buffer_manager.ts, src/test/runTest.ts, src/test/suite/index.ts, src/test/utils.ts
Closes #1432 
This opens a document, with a proper buffer name and matches it to the appropriate neovim external buffer.
The document is "readonly" as far as VSCode is concerned, but it can still be edited by setting `modifiable`, so we still need to sync buffer changes whenever it updates. This can break highlighting, however. I'm not sure if there's a way to force `nomodifiable` permanently, but it is already set for all external documents by default
Some things I haven't tested yet (would be grateful if others who use these features could test for their use cases), as mentioned in #1432 :
- I think `:marks` shows up in the output panel so is unaffected by this change
- `q:`, `q/` etc I couldn't get to work even without my changes. Are these expected to be functional?
- lazy.nvim; I …
=> Implement external buffer document provider

src/main_controller.ts
=> fix(config): ignore init path when nvim running in clean mode

runtime/lua/vscode-neovim/api.lua, src/document_change_manager.ts
For dotrepeat, sometimes the buffer is not cleared properly.
Reproduction steps:
1. Open multiple files.
2. Select a file and start editing, making sure not to exit the insert mode. Instead, switch directly to another file for editing and then exit the insert mode.
3. Repeat step 2.
=> fix: cleanup temporary buffers for dotrepeat

src/main_controller.ts
Allow users in need to extend existing functionality by creating their own vscode extensions.
=> chore: register internal command `_getNeovimClient`

runtime/lua/vscode-neovim/highlight.lua
The improvement effect is very good:)
The test patch, should enable `syntax`
```diff
diff --git a/src/highlight_manager.ts b/src/highlight_manager.ts
index 256c008..e4eb979 100644
--- a/src/highlight_manager.ts
+++ b/src/highlight_manager.ts
@@ -135,6 +135,7 @@ export class HighlightManager implements Disposable, NeovimRedrawProcessable {
// !But since changes are asynchronous and will happen after redraw event we need to wait for them first
this.main.changeManager.getDocumentChangeCompletionLock(editor.document).then(() => {
const hls = this.highlightProvider.getGridHighlights(editor, grid, gridOffset.line);
+                console.log([...hls.keys()].length);
for (const [decorator, ranges] of hls) {
editor.setDecorations(decorator, ranges);
}
```
=> perf(highlight): avoid redundant highlight IDs

src/status_line.ts
If you don’t like this change, how about adding a new configuration option? :(
=> fix: position statusBarItem in the middle

src/buffer_manager.ts, src/command_line.ts, src/commands_controller.ts, src/cursor_manager.ts, src/custom_commands_manager.ts, src/document_change_manager.ts, src/eventBus.ts, src/highlight_manager.ts, src/main_controller.ts, src/mode_manager.ts, src/neovim_events_processable.ts, src/viewport_manager.ts, vim/vscode-neovim.vim, vim/vscode-scrolling.vim
Remove `NeovimExtensionRequestProcessable` in favor of `eventBus.on`
~~Not sure if it's better than before.~~
=> refactor: use event bus for vscode-neovim events

package.json, scripts/keybindings/5 widgets.cjs, src/command_line.ts, src/command_line_manager.ts, src/eventBus.ts
fix(cmdline): use Ctrl+n/p to select candidates when candidates exist
New context: `neovim.wildMenuVisible`
Resolve: #991
=> fix(cmdline): handle `wildmenu_hide` event

src/actions.ts
`neovim:addSelectionToNextFindMatch`
`neovim:editor.action.addSelectionToNextFindMatch`
vs
`neovim-action.addSelectionToNextFindMatch`
`neovim-action.editor.action.addSelectionToNextFindMatch`
=> chore: change the action command prefix to `neovim:`

package.json
This should improve discoverability by ranking higher in the vscode search, because of the "vim" keyword.
=> chore: rename extension description

package.json, src/actions.ts, src/buffer_manager.ts, src/command_line.ts, src/command_line_manager.ts, src/commands_controller.ts, src/config.ts, src/cursor_manager.ts, src/document_change_manager.ts, src/eventBus.ts, src/extension.ts, src/highlight_manager.ts, src/highlight_provider.ts, src/logger.ts, src/main_controller.ts, src/mode_manager.ts, src/multiline_messages_manager.ts, src/status_line_manager.ts, src/typing_manager.ts, src/utils.ts, src/viewport_manager.ts
New commands:
- `vscode-neovim.restart` => Restart the extension
- `vscode-neovim.stop` => Stop the extension
Removed the following commands:
- `vscode-neovim.enable`
- `vscode-neovim.disable`
- `vscode-neovim.toggle`
Resolve #250
=> feat: Add vscode commands "restart" and "stop"

src/cursor_manager.ts
As there are no screenshots provided in #901, I'm not sure if the issue is caused by the output, but it is highly probable. Because when I encountered the "Cursor position outside buffer" error, I mostly opened the output.
- Related #1416
- Close #901
=> fix(cursor): ignore cursor position errors in the output

runtime/lua/vscode-neovim/default-options.lua
Let users set these options themselves if they need to.
by default:
autoindent: on
smartindent: off
- Related: #695
=> chore: use the default indentation options

README.md, runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/api.lua, runtime/plugin/code_actions.lua, vim/vscode-code-actions.vim, vim/vscode-neovim.vim
feat: refactor `==` and `gc`, support motions and dotrepeat
close #1422
=> feat(api): add `vscode.to_op`

package.json
I think we should use "onStartupFinished" instead of "*"
1. Better user experience.
2. vscode-neovim needs to perform some synchronization work during initialization, which may cause issues when VSCode is restoring the workspace state(not sure, but it seems possible).
=> chore: use "onStartupFinished" for activation

src/highlight_manager.ts, src/mode_manager.ts, src/viewport_manager.ts
- Resolve: #1149
- Resolve: #1555
=> fix(incsearch): viewport is not updating during searching

runtime/lua/vscode-neovim/internal.lua, src/cursor_manager.ts, src/test/suite/visual-modes.test.ts
improvement: the selection direction is consistent with nvim
Issue - Fixed
=> fix(blockwise-visual): handle double-width chars and tabs

README.md
Problem:
The docs over-explain key bindings and command aliases, which
1. is a maintenance burden
2. makes it harder to find useful info in the readme
Solution:
- Show users how to use vscode features to find keybindings instead of explaining the full details of every mapping.
- Commands like `:write` and `:split` are expected to work as well as possible, there's no need to explain the low-level details of each case.
=> docs: declutter keybindings reference

CONTRIBUTING.md, README.md
ran prettier.
also some more doc rearrangement
(sorry, should have marked https://github.com/vscode-neovim/vscode-neovim/pull/1620 as draft. This is the last of the changes.)
=> docs: lint, move keybindings to common section

runtime/lua/vscode-neovim/highlight.lua, src/highlight_provider.ts
Fixes: #1625
We cannot directly replace all highlights that contain custom highlight groups. This will cause highlights that are mixed with multiple highlights to not be displayed correctly.
=> fix(highlight): Identify custom highlight group correctly

runtime/lua/vscode-neovim/highlight.lua, src/highlight_provider.ts
Fixes #1631
The most ideal solution is to set all highlights in nvim, but it is difficult to do without the vscode API, unless we give up using the VSCode's ThemeColor. Please vote for https://github.com/microsoft/vscode/issues/32813
=> fix(highlight): Do not clear custom highlight groups directly

src/buffer_manager.ts, vim/vscode-tab-commands.vim
Fixes #1548
Rework `tabnew` to correctly replicate behaviour. For now an active workspace is required to provide a directory if the file is saved.
=> fix: rework `:tabnew`

package.json, runtime/lua/vscode-neovim/highlight.lua
With https://github.com/vscode-neovim/vscode-neovim/pull/1597, applying the `Visual` highlight is no longer needed, we can entirely rely on vscode's selection.
=> fix(highlight): remove duplicate visual selection highlight

src/buffer_manager.ts
This event is triggered by our layout sync, skip it
Fix #1594
=> fix: skip window changed when target window id is 1000

src/cursor_manager.ts, src/document_change_manager.ts
Fix #1673
---
document_change_manager also needs to be refactored, and locks should be simplified...
=> fix: Fix forcing sync editor selections

README.md, runtime/modules/clipboard.lua, src/actions.ts
Use the VSCode clipboard by default in WSL
Close #103
=> feat: Add clipboard provider `g:vscode_clipboard`

README.md, package.json, scripts/keybindings/5_widgets.cjs
- h/j/k/l
- gg/G
- C-f/C-b
- When hover is invisible, K is sent to nvim(show hover); when hover is visible, press K again to focus the hover widget.
Resolve #1681
=> feat(keybindings): Add keybindings for the hover widget

package.json, src/config.ts, src/main_controller.ts
The main idea: Save the config to a temporary file, and then use nvim's startup option -c and command source to load the file.
This configuration is suitable for simple operations such as configuring mappings in a temporary environment, but it can also execute any logic. The reason for using "after" is to avoid conflicting with existing configurations, and at the same time, it can be used to determine whether local configurations have been loaded in this configuration, thus executing different logic.
In addition, this configuration will not be automatically ignored based on neovimClean. Users can use "finish" on the first line to end the logic.
Close #1350
=> feat: Add option `afterInitConfig`

src/buffer_manager.ts
Not sure if this can truly fix a certain problem, but theoretically it will improve a bit by clearing the buffer in time.
=> fix(buffer): sync layout on doc closed

runtime/modules/ui.lua, src/actions.ts, src/test/suite/vscode-integration-specific.test.ts
Override the default vim.ui interfaces using the QuickPick and InputBox APIs. Uses two new actions, ui_select and ui_input to wire up the ui functions.
* Previous pull request: https://github.com/vscode-neovim/vscode-neovim/pull/1709
=> feat: override the default vim.ui interfaces

runtime/modules/treesitter.lua
issue #1700
This is a common use case, and "treesitter-objects" is useful. (Note: I haven't explored why treesitter doesn't automatically parse after text changes.)
=> fix(treesitter): manually trigger parsing

.github/ISSUE_TEMPLATE/bug_report.yml, README.md
We don't want to document every setting in the readme, but for issue triage it's important that we have a reference to link to, which explains `vscode-neovim.neovimClean`.
=> docs: mention "vscode-neovim.neovimClean"

.github/ISSUE_TEMPLATE/bug_report.yml, CONTRIBUTING.md, README.md, package.json, src/cursor_manager.ts, src/document_change_manager.ts, src/extension.ts, src/logger.ts, src/main_controller.ts, src/messages_manager.ts
- Introduce `Logger.info()` and "info" log-level.
- Cleanup settings descriptions.
- Create outputChannel as a `{ log: true }` channel for enhanced rendering and features.
- Allow the logger to log to the vscode Output channel. 
- But disable it for noisy (and looping) sources like `CursorManager` and `DocumentChangeManager`.
=> feat: expose logs in OutputChannel, log info on startup

.vscode/launch.json
Enabling other extensions during debugging is incredibly irritating.
=> build: pass --disable-extensions during debugging

CONTRIBUTING.md, src/buffer_manager.ts, src/logger.ts, src/utils.ts
BufferManager log messages can cause an infinite loop. #1788
- Pass the document URI to the BufferManager logger so that it can detect when a log message was triggered by the OutputChannel itself (causing a loop).
- Expand the `isLogSink` condition so that it can detect the OutputChannel even if its URI is nonsense such as `/my/workspace/path/output:asvetliakov.vscode-neovim.vscode-neovim`.
Fix #1788
=> fix(logging): infinite loop in BufferManager

CONTRIBUTING.md, package-lock.json, package.json, src/test/suite/index.ts
Problem:
`glob` is only used by the test runner, which was likely copied from the starter code provided by vscode docs.
Solution:
Use vscode `findFiles()` and remove `glob` dependency.
=> build: remove "glob" dependency

CONTRIBUTING.md, README.md, runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/api.lua, runtime/modules/clipboard.lua, runtime/modules/ui.lua, src/actions.ts, src/actions_eval.ts, src/test/suite/actions.test.ts, src/test/suite/index.ts, src/test/suite/yanking.test.ts, vim/vscode-neovim.vim
This PR introduces `vscode.eval()` which can be used to evaluate javascript passed as a string from lua. This can then be used to interact with the vscode API from neovim.
~~This PR introduces `vscode.get()` which can be used to obtain javascript values from lua. This is a simpler implementation than I originally imagined, but providing full API access including the ability to call arbitrary functions would be very complex and potentially error prone. `vscode.get()` is sufficient for the purposes of my original issue.~~
Fixes: https://github.com/vscode-neovim/vscode-neovim/issues/1760
=> feat: `vscode.eval()`

README.md, runtime/lua/vscode-neovim/api.lua, src/test/suite/actions.test.ts
as mentioned here https://github.com/vscode-neovim/vscode-neovim/pull/1854#issuecomment-2018676517 I accidentally didn't handle the `timeout` parameter to `eval()` properly. This PR fixes the issue and adds a unit test.
=> fix: handle timeout in eval properly

README.md, src/actions_eval.ts
Prevent `vscode` from becoming `null` during build. Fixes: https://github.com/vscode-neovim/vscode-neovim/issues/1864
Observations:
- with `import vscode from "vscode"`, the name `vscode` is completely removed.
- with `import _vscode from "vscode"; const vscode = _vscode;`, the name `vscode` is set to null at build time.
- with `const vscode = require("vscode")`, everything works but `vscode` is identified as unused and linters prefer `import` over `require`.
Instead of relying on require to not have the global removed, I think the most robust solution is to make sure the static analysis tools don't think any of these variables are unused in the first place. The most correct approach in the presence of `eval()` is for the tools to assume nothing, but that isn't what happens in practice. …
=> fix: vscode null in eval

README.md, package.json, src/config.ts, src/test/integ/composite-escape.test.ts, src/typing_manager.ts
The main idea is to always register the `type` command, but when there is no need to take over user input (generally in insert mode), forward the received inputs to the `default:type` command.
The implementation is to judge the input before forwarding. If it matches, call the configured command, otherwise continue to forward to the `default:type`
At present, this implementation is normal, but it feels that forwarding input causes a slight delay in input (this may be a psychological effect). Need help testing this. **If there is indeed a delay, consider forwarding inputs only when the user needs the composite keys. If the user does not need to use composite keys, then just dispose the command when there is no need to take over user input**. ( Even if there is a delay, it is very slight.) …
=> feat!: better composite key support

README.md, src/typing_manager.ts
Also add a deprecated notice to the old `compositeEscape1` and `compositeEscape2` commands
- close #1929
- link #1926
=> docs: Improve documentation and examples for composite keys

src/typing_manager.ts
At present, the problem in #1921 seems to be unavoidable. The current approach is that when composite keys are not used, the logic is the same as before. See if users can accept it  @theol0403 @wenfangdu @vlwkaos
=> refactor: register type commands only when needed

src/status_line_manager.ts
Fix #1572 (probably related: #1251 #843)
A similar issue can be observed in combination with other extensions
The issue https://github.com/microsoft/vscode/issues/201795 causes status bar items to clash if they are created without explicit ids and in different extension hosts (e.g. by setting extension affinity).
While the underlying issue is not fixed, it can be avoided by assigning an explicit id (and there are no downsides to doing this, as far as I am aware).
=> fix: set an explicit id for status bar item

runtime/lua/vscode-neovim/highlight.lua
- Always try stopping treesitter highlight for all buffers
Possibly not focusing on window after creating it, e.g. when using the peek window
=> fix: should setup highlights on WinNew,BufNew

.husky/pre-commit
Whoops, I missed this during the pre-commit migration in #1949
=> build: re-add `npm run keybind` to hooks

runtime/lua/vscode-neovim/highlight.lua
This looks like a missed case from #1944; it intended to add `WinNew`, `BufNew`, but seemingly accidentally removed `WinScrolled`!
Fixes #1963
=> fix: setup highlights timely

CONTRIBUTING.md, package.json, src/buffer_manager.ts, src/document_change_manager.ts, src/extension.ts, src/logger.ts
After my confusion [here](https://github.com/vscode-neovim/vscode-neovim/discussions/1952), I changed the extension logging to use the VSCode setting, rather than our own. This also removes the `logLevel` setting we previously had.
The biggest change here, by far, is the movement from our `LogLevel` to the VSCode `LogLevel` (which unfortunately, reverses the order of the levels! Argh!)
=> feat!: use VSCode log level instead of our own

src/cursor_manager.ts, src/viewport_manager.ts
- close #1969
Temporary solution. Need to refactor cursor manager and viewport manager. Merge the logic and redefine the necessity of some custom events, such as visual-changed and window-scroll.
Note: Handling the win_viewport event directly in the cursor manager does not work
=> fix(incsearch): win cursor not properly revealed

eslint.config.cjs, src/actions_eval.ts, src/eventBus.ts, src/extension.ts, src/logger.ts, src/main_controller.ts, src/test/integ/extmark.test.ts, src/test/integ/integrationUtils.ts, src/typing_manager.ts, src/viewport_manager.ts
I'm still in my linting rabbit hole for right now... I've gone ahead and enabled the `recommendedTypeChecked` rules in the linter. I want to eventually move towards `strictTypeChecked` (especially rules like [`no-unnecessary-condition`](https://typescript-eslint.io/rules/no-unnecessary-condition), which are very helpful for catching bugs), but one step at a time.
You can view the rules which are enabled, here https://typescript-eslint.io/rules/?=recommended-typeInformation
There are some code changes involved here, but I'm fairly confident they won't cause any issues. You can review the commits individually to better understand why each change was made
=> build: enable recommended typechecked rules

.github/workflows/build_test.yml
Closes #1980. I must admit, I'm no Homebrew expert (I actually don't have a mac handy), but from my testing (and reading of the [man page](https://docs.brew.sh/Manpage#update-options) this forces Homebrew to update its caches every time the CI runs. The only downside (aside from time) is it also upgrade Homebrew itself, which may not be fully desirable, but unfortunately I don't think there's a way to tell homebrew to only upgrade formulae (i.e. there is no equivalent to `apt-cache update` or some such)
=> ci: update homebrew formulae before running tests

package.json, runtime/lua/vscode-neovim/highlight.lua
chore: remove the border of the custom highlights
It will be strange when multiple decoration ranges with borders are connected.
- Fix #1979
=> fix: set highlight group Subsitute

package.json, runtime/lua/vscode-neovim/default-options.lua, runtime/modules/inccommand.lua, src/cmdline/cmdline_controller.ts, src/cmdline/cmdline_text.ts, src/config.ts
fix: wildmenu sometimes not showing
https://github.com/vscode-neovim/vscode-neovim/assets/47070852/46b01ac0-09d7-4866-8c9b-a0a0b40be009
=> fix: Support inccommand, including "split"

src/test/unit/highlights/highlight_grid.test.ts, src/utils/text.ts
=> fix(highlight): fix eol highlight not displaying

CONTRIBUTING.md, package.json
One thing I've noticed when building the extension to try out existing PRs is that it's extremely annoying to downgrade back to the "production" version from the marketplace (you either have to rebuild at the old tag, or clear out some VSCode package caches by hand). I added `npm run build:dev`, which should help ease this experience
=> build: add helper to build dev version of extension

package.json, runtime/lua/vscode-neovim/highlight.lua
Edits https://github.com/vscode-neovim/vscode-neovim/pull/1983
* `editor.findMatchBackground`: Color of the current search match.
* `editor.findMatchHighlightBackground`: Color of the other search matches. The color must not be opaque so as not to hide underlying decorations.
I believe most themes will not have transparency for findMatchBackground
=> refactor: don't hardcode substitute highlight

CONTRIBUTING.md, runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/viewport.lua, src/eventBus.ts, src/highlight_manager.ts, src/test/integ/highlights.test.ts, src/test/integ/incsearch.test.ts, src/test/integ/vscode-integration-specific.test.ts, src/viewport_manager.ts, vim/vscode-neovim.vim
- fix: cursor position after scrolling with incsearch
- refactor: remove viewport hack when in cmdline mode
---
- Close #1975
- Fix #161
- Related:
- #1575
Because it involves a few historical matters and dealing with hacks, I won't go into too much detail. Here are some debugging notes.
| Commit History                                         | Nvim 0.9 | Nvim 0.10 |
| ------------------------------------------------------ | -------- | --------- |
| Add test                                               | ❌       | ✅        |
| Remove hack                                            | ❌       | ✅        |
| Update cursor position on window-scroll                | ❌       | ✅        |
| Fire cursor change event on window-scroll              | ❌       | ✅        |
| custom viewport changed …
=> fix(highlight): forward search / matching in long lines

src/cmdline_manager.ts
Current behaviour:
* user triggers cmdline completions
* user selects a suggestion with the mouse
* onSelect sets a flag to inhibit onAccept
* onAccept is triggered (because of the mouse click, for some reason), but inhibited
* the user can keep typing
Current problem:
* user selects suggestion with C-n/C-p
* for some reason, vscode moves the focus to the suggestions, not the input
* pressing CR triggers onSelect before onAccept
* onAccept is inhibited, so CR stops working
To fix this, now, when selecting a suggestion with the mouse, it accepts the cmdline and runs the command. Not ideal, but not an important use case.
=> fix(cmdline): allow enter to accept cmdline after completion selected

README.md, package.json, src/config.ts
Should we also remove the composite escape related content? Although it was added recently, I believe that most users have already completed the migration.
=> refactor: clean up deprecated content

CONTRIBUTING.md, src/extension.ts, src/main_controller.ts, src/messages_manager.ts
Fixes #1965. 
I added a second channel, `vscode-neovim (messages)`, and renamed the existing one to `vscode-neovim (logs)`. Messages are sent to both locations, which preserves timestamps. While right now the `vscode-neovim (messages)` channel is a bit barebones, I'm hoping to do some tweaks to make it more useful. Stay tuned on that :)
=> feat: move output messages to a separate channel

src/messages_manager.ts
This PR builds on #2022 ~(sorry for the redundant commits... couldn't find a good way to stack the PRs).~
The idea here is that the output channel can be used to emulate the bottom split window in nvim after calling `messages`, or a statusline. 
A video's worth a thousand words: 
https://github.com/vscode-neovim/vscode-neovim/assets/977151/de2b7376-1de5-4dc6-b8c5-c3416b3e6756
A few notes on what you're watching here
1. If the output panel is open, a `msg_show` will be the only thing shown
2. If the output panel is closed, single-line output will not open the panel
3. multi-line output or command history will show the output panel 
Of course, you can still view historical outputs in the logs channel.
=> feat: revamp messages output channel

src/messages_manager.ts
Just a small QoL change in face of #2024. If nvim is sending us a `return_prompt` event, the output we have is probably meaningful enough to show to a user, so we should pop out the output channel. This is useful for things like `!`, which might only have one line of output (and thus wouldn't normally display)
=> feat: show output when return_prompt is sent

src/extension.ts
When you execute the `vscode-neovim.restart` command, duplicate output channels appear.
=> fix: correctly dispose the output channels

src/cmdline_manager.ts, src/test/integ/command-line.test.ts
Replaces #2030 
Fixes #2028
When we get cmdline_show events, we're informed of how "deep" our commandline is. Using this is a little more robust than trying to toy our way around what events to ignore. As a result, handling nested command lines is much easier :)
Also, I guess my branch name is wrong, but oh well :)
=> fix: account for level when handling cmdline_hide events

runtime/vscode/overrides/vscode-file-commands.vim, src/buffer_manager.ts, src/test/integ/vscode-integration-specific.test.ts
~~This is definitely _not_ fully tested, but is something I was playing around with~~ I wanted to throw out this there to see if there was any something I hadn't considered here :) It's a pretty fundamental change, so I'd love eyes from those who know more than me :D
Should also address #521. I was able to run `w !wc -c` on an unsaved buffer and get the output, without kicking up a save dialog
I've been running this for a bit with no major issues, but would love some soak testing help
=> refactor: remove Altercmd for "write"

README.md, runtime/lua/vscode.lua, runtime/lua/vscode/api.lua, src/test/integ/lua-with-insert.test.ts
fix #1999
Compared to #2052, the callback function is no longer optional, which makes it simpler and easier to understand and maintain.
=> feat(lua): Add "vscode.with_insert"

src/messages_manager.ts
=> fix: don't show output panel after return_prompt, reverts #2029

src/main_controller.ts
fixes #2058
**Problem**: We missed the situation where vscode-neovim runs on the remote extension host in remote development.
**Solution**: Set it.
=> fix: Fix setting the cwd in remote development

eslint.config.cjs, src/buffer_manager.ts, src/config.ts, src/cursor_manager.ts, src/extension.ts, src/logger.ts, src/main_controller.ts, src/test/integ/actions.test.ts, src/test/integ/highlights.test.ts, src/viewport_manager.ts
I chose to use the [`smart`](https://eslint.org/docs/latest/rules/eqeqeq#smart) value of the `eqeqeq` rule, as there are some contexts (e.g. `!= null`) where it is desirable to use `eqeq`.
I took a look at these usages, and I don't believe any of them have caused any bugs as-is, but we may as well try to prevent bugs by enforcing this rule.
=> style: require eqeqeq in most contexts

package.json
I found `"vscode-neovim.normalSelectionDebounceTime": 100` is not enough for completely getting rid of https://github.com/vscode-neovim/vscode-neovim/issues/1752.
`200` is the max limit for `vscode-neovim.mouseSelectionDebounceTime` too, might be sufficient.
=> fix: remove maximum debounce time for normal selection

README.md
Clarifies a quirk of neovim output that changed between 0.9.x and 0.10. Thanks to @iansinnott for [pointing it out!](https://github.com/vscode-neovim/vscode-neovim/issues/2046#issuecomment-2155828299)
=>  docs: add configuration compatibility section to README 

src/buffer_manager.ts
Synchronous layout operations take some time, and even with debouncing and a CancelToken, it's not guaranteed that only one synchronous operation will run at a time. If multiple synchronous operations are executed simultaneously, conflicts can occur, especially when initializing the buffer, leading to errors when setting the buffer name.
=> fix(buffer): prevent concurrent syncs and stale data

src/highlight_manager.ts, src/highlights/highlight_grid.ts
fix #2111
We should still wait for the document synchronization to complete before calculating the highlights. Otherwise, there is a possibility of computing incorrect highlights due to inconsistent content. Previously, this logic was mistakenly deleted.
=> fix(highlights): wait for doc changes before updating highlights

src/messages_manager.ts
fix #2109
This version difference does affect maintenance  :(
=> fix(messages): Limit the minimum value of `cmdheight` to 1

README.md, runtime/lua/vscode/internal.lua, runtime/vscode-neovim.vim, runtime/vscode/overrides/vscode-file-commands.vim, src/buffer_manager.ts, src/test/integ/buffer-write-cmd.test.ts, src/test/runIntegrationTest.ts, src/utils.ts, src/utils/fs.ts, src/utils/index.ts
=> feat: Integrate BufWriteCmd for "write" command

src/viewport_manager.ts
This log is redundant and misleading. When synchronizing the Editor, the grid corresponding to the created window definitely doesn't exist yet.
=> chore: remove useless log for viewport change

src/cmdline/cmdline_queue.ts, src/cmdline_manager.ts, src/test/integ/command-line.test.ts, src/test/unit/cmdline/cmdline_queue.test.ts
Replaces #2081
Fixes #2079 
I came up with [this idea](https://github.com/vscode-neovim/vscode-neovim/pull/2081#issuecomment-2157087672) a little while ago, but haven't had the chance to sit down and implement it. Ultimately, most problems with our two-way cmdline sync originats from the fact that a cmdline_hide can be sent before the quickpick actually executes a hide event, or vice versa. Attempting to  manipulate the events to "ignore" is error prone, given this ordering problem. 
To repeat myself a bit from the linked comment, the "idea" is that we can handle cmdline events in batches. Once we receive a cmdline_hide event at level 1 (i.e. no nested command lines), we can consider the current batch "terminated", and begin queueing up events. Then, when we get a VSCode "hide" event, we …
=> fix: rapid cmdline_show/cmdline_hides would not be handled logically

runtime/lua/vscode/sync-options.lua, runtime/lua/vscode/util.lua, runtime/vscode/treesitter.lua
- Trigger Treesitter parsing on CursorHold
- Add utility function debounce
It used to be too much consideration, which was unnecessary.
=> refactor: Simplify invoking Treesitter parsing and ensure more timely parsing

package.json
I spent around 15 minutes wondering why my Vimscript wasn't working to ignore case. Below you can see the settings for the current version of the extension, the top is the correct line and the bottom is the line I was writing:
Which maps to this in settings.json
I think I would have easily understood what to do immediately if the instructions looked like this instead:
=> refactor: Improve usability of afterInitConfig option in the settings

package.json
The settings currently look like this:
I didn't know whether enabled Ctrl keys meant for Neovim or for VS Code. This commit changes the settings to now look like this, which would have been a better explanation when I started using the extension:
=> refactor: Improve explanation of Ctrl+key in settings menu

runtime/lua/vscode/internal.lua, runtime/lua/vscode/util.lua, src/test/integ/visual-modes.test.ts
Since Nvim 0.10.0, `virtcol2col` changed from returning the last byte of a multi-byte character to returning the first byte. However, we need the column of the last byte, which is consistent with the selected region in Nvim.
Close #2166
=> fix: Fix multi-byte character selection in Nvim 0.10 blockwise visual

runtime/lua/vscode/viewport.lua
Temporary fix for #2165
It may not be completely avoided, but it can reduce the problem
=> fix: avoid unnecessary rpcnotify that cause crashs (temporary fix)

package-lock.json, package.json, src/extension.ts
First of all: thank you for your work!
This PR ever so slightly eases the latest VS Code version requirement as the code does not use any of the newer APIs the change is supposed to be fully backward compatible.
The reason I am creating this PR is due to some companies not allowing to update to the most recent VS Code version thus the VS Code marketplace for plugins does not allow to install the most recent version of this plugin and these users miss out on months of new functionality. I hope it is okay to make this change as it does not seem to cause any regression in functionality or add an additional maintenance burden.
The proposed minimum required VS Code version 1.89 is fairly recent [April 2024](https://code.visualstudio.com/updates/v1_89).
I have ran all precommit and `npx tsc` …
=> Ease engines requirement

runtime/lua/vscode/viewport.lua
Fixes #2194 
**Problem:**
Our highlight manager needs the correct offset of the current viewport. When scrolling with the mouse during `incsearch`, the offset sometimes becomes outdated. This happens because the `viewport-changed` event isn't triggered, and the 'win_viewport' event occurs after the `grid-line` event. As a result, `this.lineCells` becomes incorrect. This is problematic because we rely on accurate `this.lineCells` data when computing line highlights.
https://github.com/vscode-neovim/vscode-neovim/blob/160d7aa03cd72c59ab1a1cfa6e40a591298a549a/src/highlights/grid_line_handler.ts#L87
https://github.com/vscode-neovim/vscode-neovim/blob/160d7aa03cd72c59ab1a1cfa6e40a591298a549a/src/highlight_manager.ts#L105
**Solution:**
Trigger `viewport-changed` to get a up-to-date viewport
=> fix: handle `topline` in the `viewport-changed` event

package-lock.json, package.json, src/extension.ts
Reverts vscode-neovim/vscode-neovim#2163
The singular support release has been completed, so we can roll back to our higher engine version
=> Revert "Ease engines requirement"

README.md
I've installed nvim as a snap package and VSCode could not detect automatically. This is because the Ubuntu 2204 package is 0.6, which is further behind than this extension recommends. 
A bit of googling found that snap stores the binary at: /snap/nvim/current/usr/bin/nvim
Updated the README as people may install from Ubuntu Store which uses snap.
=> docs: update README.md with snap installation details

README.md, runtime/lua/vscode/default-options.lua, src/constants.ts, src/eventBus.ts, src/messages_manager.ts, src/test/integ/messages.test.ts
Closes #2134 
`:help ui-messages` shows a lot more details about how these messages are meant to be handled. This change makes our handling match more closely to the expected behavior and now obeys *_clear types of messages as well.
This changes the behavior of message handling pretty significantly, so it probably deserves some more serious testing before merging into a release — especially given some of the issues that have shown up in the past re: `return_prompt` + `cmdheight`, etc.
Keeping this as a draft for now as I'm still seeing an issue in some case where `:messages` (i.e. `msg_history_show`) gets cleared immediately after writing, resulting in no visible output. Seems to be sent due to https://github.com/neovim/neovim/issues/12929 maybe we should just ignore it, or treat it …
=> refactor: follow nvim ui-messages protocol

runtime/lua/vscode/internal.lua, src/buffer_manager.ts, src/messages_manager.ts
Workaround for #2136
This isn't really fixing the problem, since I haven't been able to figure out the root cause yet, but this should at least allow the cleanup handler to move on and restore control to the user after a few seconds.
Also got rid of the lua layer for the window cleanup, since we can just call the nvim APIs directly without an extra indirection (I had hoped that itself might fix the issue but alas did not).
Also ensure messages output channel is cleaned up by registering its `dipsose()` call. I think I broke this in #2177 (oops!)
----
Edit: for testing, I've been driving this a version of this change to see if it helped the UX and it did in fact help! My editor remained usable after the timeout, instead of forcing me to restart the extension like I usually do:
``` …
```
=> fix(buffers): don't await window/buffer cleanup

src/extension.ts
Recent improvements to the README.md changed some section titles, which changed the page anchors for deep linking.  This corrects a broken link in verifyExperimentalAffinity() when the default affinity is set.
In preparing this PR, I checked for any other links to "vscode-neovim#" or "README.md" within the codebase and didn't find any other links that might need updating.
=> fix: update link to #performance docs from vscode affinity prompt

runtime/lua/vscode/sync-options.lua, runtime/lua/vscode/util.lua
With the config below, entering and exiting Insert mode causes the `OptionSet` event to trigger repeatedly, leading to a loop.
```lua
vim.opt.number = true
vim.api.nvim_create_autocmd("InsertEnter", {
pattern = "*",
callback = function()
vim.wo.relativenumber = true
end,
})
vim.api.nvim_create_autocmd("InsertLeave", {
pattern = "*",
callback = function()
vim.wo.relativenumber = false
end,
})
```
Demonstration Videos:
[Link](https://1drv.ms/v/s!AkmEvT_Y9oQ6gcJBEggsXLzWsZJP_g?e=3l06EI)
The `OptionSet` keeps triggering.
[Link](https://1drv.ms/v/s!AkmEvT_Y9oQ6gcJA16bZRkHnPX7qGQ?e=82s8Vb)
Note: This may not fully address #2267(not sure this is the root cause, in my case, vscode-neovim is not locking up in insert mode), but it does fix the looping OptionSet event in this scenario.
=> fix: prevent loop on OptionSet

src/actions.ts
vscode exthost logs may show error, when user changes windows during startup:
2024-10-16 13:46:16.857 [error] Error: [ExtensionListenerError]
Extension 'asvetliakov.vscode-neovim' FAILED to handle event:
TypeError: Cannot read properties of undefined (reading 'command')
- Handle undefined `this.client`.
- TODO: where is `this.client` ever actually defined?
=> fix(startup): null reference in `onDidChangeWindowState` handler

runtime/lua/vscode/internal.lua, src/test/integ/buffer-write-cmd.test.ts
The existing behavior caused a mix of "symbolic" paths and physical paths to be used when saving buffers, which causes incorrect relative path resolution. Take this example structure:
/home/me/coding/git/vscode-neovim
/mnt/coding
where "/home/me/coding" is a symbolic link to "/mnt/coding".
The current behavior will mix up "/mnt/coding/git/vscode-neovim/README.md" and "/home/me/coding/git/vscode-neovim/README.md" when attempting to save the README, causing the incorrect destination path to be resolved and throwing an error when attempting to save.
The new behavior uses Neovim's default behavior of resolving "symbolic" paths to physical paths so only "/mnt/coding/git/vscode-neovim/README.md" will be used when determining destination file path.
Note that the test-case I've added doesn't 100% …
=> fix(buffers): Fix saving to files inside symlinked workspaces

README.md
Fixed the issue where the `see below` link in the `💡 Tips and Features` section was not working
<details>
<summary>日本語</summary>
`💡 Tips and Features`セクションの`see below`のリンクが機能していなかったのを修正
</details>
=> docs: Fixed link to keybindings section

.github/dependabot.yml
dependabot autoupdates `@types/vscode` as part of the "dev-deps" group, which causes CI to fail unless we bump `engines.vscode`. This would require us to aggressively bump our minimum supported vscode version:
Error: @types/vscode ^1.95.0 greater than engines.vscode ^1.90.0. Either upgrade engines.vscode or use an older @types/vscode version
Error: Process completed with exit code 1.
Tell dependabot to ignore `@types/vscode`.
TODO: put it in a separate "group" so that dependabot creates a separate PR for it, which we can merge as needed.
=> ci: dependabot should skip `@types/vscode`

README.md, package.json, scripts/keybindings/1_common.cjs, scripts/keybindings/2_normal_mode.cjs, scripts/keybindings/3_insert_mode.cjs, scripts/keybindings/4_cmdline.cjs, scripts/keybindings/util.cjs
TLDR: This fixes an issue on macOS and non-US keyboard layout (e.g. Czech), where the corresponding Ctrl code is not correctly recognized. (discussed in #1875).
Long version:
When pressing `Ctrl+<key right to P>` on a keyboard with non-US layout (e.g. Czech), which would be `Ctrl+[` on US layout, this key maps to `<C-[>` in `vim` and `neovim` on Windows and macOS.
This was not working in `vscode-neovim` on macOS (but did work in Windows) for some reason which most likely stems from internal VSCode implementation and how VSCode does (or does not) handle the localized keyboard layouts in particular OS. The observed difference is noted [here](https://github.com/microsoft/vscode/issues/237533).
It appears that both VSCode versions (on macOS and Windows) maps the aforementioned keypress to …
=> fix(defaults): keybindings for ctrl+[BracketLeft], ctrl+[BracketRight] as alternatives for ctrl+[ and ctrl+].

src/test/integ/integrationUtils.ts
Through simple testing, it seems that this action often does not work in tests (VSCode 1.98.0 and later versions).
=> fix(test): use custom `clipboardCopyAction` implementation

src/cursor_manager.ts, src/test/integ/integrationUtils.ts, src/test/integ/visual-modes.test.ts
fix: Fix assertContent cursor position parameter
fix #2299
@theol0403 Previously, the visual model only exited after a mouse click. Was there any special consideration for this?
=> fix: exit visual mode on mouse click or selection cancel

runtime/lua/vscode/force-options.lua
fix #2441 
This option interferes with highlighting, and we don’t need it.
=> fix: force `winborder` to `none`

src/buffer_manager.ts
Ignore editors without a ViewColumn in Neovim 0.10 and above to avoid issues caused by too many editors leading to RPC problems.
At present, [this](https://github.com/vscode-neovim/vscode-neovim/pull/2394/commits/54bb04ed3e0d5adc65e7589e8d4add91696c03f2) is the simplest and most useful approach. The difference is that keeping the activeEditor synchronized at all times is more accurate.
fix #2407
=> fix: ignore editors without `ViewColumn` in nvim-0.10

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Problem:
Github issues now has a `type` but we are still using the old labels.
Solution:
- Update the issue templates.
- Also ask for VSCode version.
=> docs: issue templates
