vscode-neovim/vscode-neovim

vim/vscode-window-commands.vim
Change duplicated mapping presumably caused by typo.
=> Fix missing <C-w>c mapping

vim/vscode-file-commands.vim, vim/vscode-tab-commands.vim, vim/vscode-window-commands.vim
fix https://github.com/asvetliakov/vscode-neovim/issues/192
=> support completion for basic commands

README.md
I had to scour the internet for a while to figure out how to get the keys to repeat.  Thought I would add it to your documentation for others.  Cheers!
=> This PR is simply for documentation purposes only

vim/vscode-options.vim
References #291 and closes #230.
=> Fix shortmess

package.json, vim/vscode-code-actions.vim
=> Add gO and K mappings

src/buffer_manager.ts, vim/vscode-options.vim
=> Do not unload buffers

.github/workflows/build_test.yml
This will build extension on every PR and allow users to download it. [Example](https://github.com/asvetliakov/vscode-neovim/actions/runs/245120004).
=> Add CI artifacts

src/cursor_manager.ts, src/test/suite/vscode-integartion-specific.test.ts
=> Fix search cursor

src/cursor_manager.ts, src/status_line_manager.ts, src/test/suite/vscode-integartion-specific.test.ts
Fix #372 
Not sure if there is a better trust source here, but seems doing the trick
=> Accept return prompt only when necessary

README.md
=> Fix `kk` to `jk`

README.md
Reverts asvetliakov/vscode-neovim#400
=> Revert "Fix `kk` to `jk`"

README.md
Check default linux distribution
=> Small Addition to the README for checking the default linux distribution

src/buffer_manager.ts, src/test/suite/undo.test.ts, vim/vscode-options.vim
https://github.com/asvetliakov/vscode-neovim/pull/461#issuecomment-751948648
=> do not delete buffers automatically

src/cursor_manager.ts
=> Fix word HL after setting cursor directly

src/main_controller.ts, src/mode_manager.ts, src/test/suite/visual-modes.test.ts, src/test/suite/vscode-integartion-specific.test.ts
=> Cancel current mode when switching to other editor

src/cursor_manager.ts, src/test/suite/multi-byte-chars.test.ts
=> Fix multi-column character handling

src/cursor_manager.ts
=> Fix tab indents

vim/vscode-window-commands.vim
=> Also close the window on ctrl+w ctrl+c as expected

.eslintrc.js, package.json, src/document_change_manager.ts, yarn.lock
This commit upgrades the dependencies using [npm-check-updates](https://www.npmjs.com/package/npm-check-updates). I'm just trying this one out in order to see where it goes wrong.
=> Upgrade dependencies

src/cursor_manager.ts
=> Always use win_viewport event and remove grid_cursor hacks

README.md, package.json, src/test/suite/insert-mode.test.ts, src/typing_manager.ts
=> Implement Ctrl-O for insert mode

README.md
When rebasing #585 I forgot to remove the outdated note (which also was in the wrong place to start with). Oops.
=> Remove c-o note (#585)

vim/vscode-file-commands.vim, vim/vscode-tab-commands.vim
=> Fix command with complete but no nargs (#724)

.prettierrc.js, README.md, package.json, src/buffer_manager.ts, src/cursor_manager.ts, src/document_change_manager.ts, src/extension.ts, src/main_controller.ts, src/test/utils.ts, vim/vim-altercmd/.travis.yml, yarn.lock
I updated yarn.lock. Lot of old things in there.
...btw, why are we using yarn?
=> build: add "vsce" dev-dependency, document build steps

src/buffer_manager.ts, src/document_change_manager.ts
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/776
Took a stab at this since I've had this happen to me as well a couple of times.
I did some tests with multiple files and tabs and it seems to work fine but I would appreciate it if someone else tried it as well 🙏  
https://user-images.githubusercontent.com/77260898/150796674-3651c6fa-5d2e-48ef-8212-818c235971c5.mov
It's my first time contributing to this amazing project so pardon me if I did something wrong. Please let me know if there is anything else that I can do for this PR.
=> Fix cursor jumps when switching split-screen tabs

src/buffer_manager.ts, src/document_change_manager.ts
Reverts vscode-neovim/vscode-neovim#808
=> Revert "Fix cursor jumps when switching split-screen tabs"

src/cursor_manager.ts
try to make on double click  working
=> fix: fix mouse double click

package.json, src/extension.ts, src/main_controller.ts
https://github.com/vscode-neovim/vscode-neovim/issues/746
allows finer control of the rtp, useful for users of https://github.com/wbthomason/packer.nvim
=> feat: `--clean` option

package.json, src/extension.ts, src/highlight_manager.ts, src/main_controller.ts
The behaviour should be default, this PR removes code bloat.
Fixes #951
=> feat: remove textDecorationsAtTop option

README.md, src/highlight_manager.ts
Run `npm run lint && npm run format`.
=> chore: lint & format codebase

README.md
Some minor changes to the readme file! Wanted to keep things consistent with how it felt the author would've wanted things. 
Just mostly changed some typical English grammatical mistakes. Made things more uniform across the document.
Love the project by the way!
=> docs(README): various grammatical fixes

src/highlight_provider.ts
Also fixes an issue where `color` was being assigned to `borderColor`
=> fact(highlight_provider): simplify `normalizeDecorationConfig`

package.json, yarn.lock
=> feat: list.toggleKeyboardNavigation => list.find

README.md, package.json, vim/vscode-code-actions.vim, yarn.lock
Support shortcut for navigate custom code action menu on VSCode >= 1.71.0
=> feat: add shortcut for navigate code action menu

package.json, src/extension.ts, src/main_controller.ts, src/utils.ts
=> feat: specify default nvim binary path

src/cursor_manager.ts
The problem was that nvim_input is async, so we were sending "v" and then moving the cursor to the end of the selection *before* visual mode was enabled.
This also simplified the logic a bit for better readability. Hopefully, I didn't break anything. 
Fixes #944, #891, #395. Closes #1043, #821.
=> fix(cursor_manager): fix mouse selection starts visual mode

src/cursor_manager.ts, src/document_change_manager.ts, src/highlight_manager.ts, src/main_controller.ts, src/mode_manager.ts, src/typing_manager.ts, src/viewport_manager.ts
This reworks dependency management and allows managers to access each other without passing through constructors and allows circular dependency.
=> fact(main_manager): allow circular manager dependencies

src/cursor_manager.ts
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1052
=> fix(cursor_manager): fix mouse selection without starting visual mode

src/highlight_provider.ts, src/test/suite/extmark.test.ts
=> fix(highlight): check highlight with blend for extmark

src/highlight_provider.ts, src/test/suite/extmark.test.ts
=> fix: remove check blend on overlay

vim/vscode-motion.vim
v:count1 defaults to 1 when the user does not use a count with the command/mapping
=> replace `v:count ? v:count : 1` with `v:count1`

.github/workflows/build_test.yml, src/main_controller.ts, src/test/suite/basic-editing-navigation.test.ts
Cherry-picked from https://github.com/vscode-neovim/vscode-neovim/pull/1110.
=> Warn for using outdated Neovim

package.json
specifically mention to use default WSL distro
fix #1237
=> change descriptions 

.github/workflows/build_test.yml
Using release-please to streamline releases. The vsce key currently does not seem to be working, however. 
Additionally, switching to SemVer versioning.
=> feat(ci): add automatic releases

src/cursor_manager.ts, src/main_controller.ts, src/mode_manager.ts, vim/vscode-neovim.vim
This gives us information for when the mode switches between kinds of visual modes. 
Based on https://github.com/vscode-neovim/vscode-neovim/pull/1254
=> feat(mode): switch to `ModeChanged` for more detailed mode information

package.json, src/mode_manager.ts
=> fix(mode): cmdline mode bindings #1298

.github/workflows/build_test.yml, src/cursor_manager.ts, src/test/suite/basic-editing-navigation.test.ts, src/test/suite/command-line.test.ts, src/test/suite/composite-escape.test.ts, src/test/suite/dot-repeat.test.ts, src/test/suite/external-buffers.test.ts, src/test/suite/external-changes.test.ts, src/test/suite/extmark.test.ts, src/test/suite/index.ts, src/test/suite/insert-mode-additions.test.ts, src/test/suite/insert-mode.test.ts, src/test/suite/jumplist.test.ts, src/test/suite/macros.test.ts, src/test/suite/multi-byte-chars.test.ts, src/test/suite/undo.test.ts, src/test/suite/visual-modes.test.ts, src/test/suite/vscode-integration-specific.test.ts, src/test/suite/yanking.test.ts, src/test/utils.ts, src/typing_manager.ts
This should cut CI duration by half. The challenge will be ensuring it has not become more flaky.
=> refactor(tests): cleanup and remove delays

runtime/lua/vscode.lua, runtime/lua/vscode/api.lua, runtime/lua/vscode/cursor.lua, runtime/lua/vscode/defaults.lua, runtime/lua/vscode/util.lua, src/viewport_manager.ts, vim/vscode-neovim.vim
This is a WIP for creating a lua API. For now, it just contains `notify` and `call`. I can't think of too many other options now, but the door is open in the future.
This attempts to properly use lua modules, though I am still unexperienced with best practices.
=> feat(lua): add lua api

src/cursor_manager.ts
=> fix(cursor): optimized cursor synchronization debouncing

src/mode_manager.ts, vim/vscode-neovim.vim
=> fix(mode): synchronize mode after startup

src/buffer_manager.ts
=> fix(buffer): avoid sync conflicts during startup

src/buffer_manager.ts, src/cursor_manager.ts
Fixed errors related to "output" in #498, but not sure if all scenarios are covered. Actually, I haven’t encountered any other situations either.
=> fix(buffer): the output document should be modifiable

src/highlight_provider.ts
Close: #1374 
https://github.com/vscode-neovim/vscode-neovim/issues/1374#issuecomment-1710047365
=> fix(highlights): fix highlights when emojis exist

runtime/lua/vscode-neovim/api.lua, src/buffer_manager.ts
=> fix: clean up buffers properly

.github/workflows/stylua.yml, .prettierignore, .stylua.toml, package.json, runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/api.lua, runtime/lua/vscode-neovim/cursor.lua, runtime/lua/vscode-neovim/defaults.lua, runtime/lua/vscode-neovim/force-options.lua, runtime/lua/vscode-neovim/util.lua, src/test/suite/extmark.test.ts
- Add stylua-action
- Exclude CHANGELOG.md from formatting
Stylua is a widely used Lua formatter in the NVIM community. Then I chose the more commonly used style. A unified style is beneficial for maintenance and contribution.
=> style: format lua using stylua

src/buffer_manager.ts
Issue #1427 still exists.
There is no need to save the visible editor, as it is redundant and may also prevent proper cleanup of windows and buffers.
Related: #1427, #1428
=> fix(buffer): Ensure proper cleanup of windows and buffers

src/cursor_manager.ts
Close #846
Issue #846 should have been fixed in both PR #1411 and PR #1417. This PR makes it more stable.
=> fix(cursor)：improve cursor style synchronization

runtime/lua/vscode-neovim/api.lua, src/document_change_manager.ts, src/test/suite/jumping.test.ts, src/test/suite/vscode-integration-specific.test.ts
Code modified from https://github.com/neovim/neovim/pull/14630
fixes #543
=> fix(buffer, change): save and restore local marks

src/cursor_manager.ts
=> fix(cursor, visual): fix sync mouse selection

src/viewport_manager.ts
@theol0403  This is a minimal patch to reduce cursor jitter. Although it is a temporary solution, it is indeed effective. I have reviewed relevant issues and pull requests regarding the viewport, but unfortunately, I don’t have enough time to contribute further. As you mentioned, you are also busy. Therefore, I suggest using this temporary solution until someone can dedicate themselves to fixing the viewport. It’s better to have something than nothing. The cursor jitter significantly impairs the functionality of the frequently used jumping feature, resulting in a very bad user experience.
bad
so-so
=> fix(viewport): reduce cursor jitter (temporary solution)

src/cursor_manager.ts
=> fix(cursor): ensure normal visual mode for mouse selection

package.json, src/command_line.ts, src/command_line_manager.ts, src/extension.ts, src/main_controller.ts
=> feat(command line): add a configurable completion timer delay

runtime/lua/vscode-neovim.lua
=> feat: hide completion widgets when leaving insert mode

package-lock.json, package.json, src/cursor_manager.ts, src/test/suite/insert-mode.test.ts, src/typing_manager.ts
This PR fixes the issue where the cursor position is not updated after exiting the insert mode in the same cursor position it was entered. Previously, this would result in the incorrect cursor position.
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/628d26af-0b67-4819-a8a7-8e4272557903
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/f7a24737-0a0c-4869-971a-8b682d08e988
=> fix(cursor): update position after exiting insert mode

runtime/lua/vscode-neovim.lua, runtime/lua/vscode-neovim/filetype.lua, src/test/suite/vscode-integration-specific.test.ts
=> feat: add filetype module

src/highlight_provider.ts
feat: optimize end-of-line highlighting rendering
Resolve: #1493
=> fix(highlight): avoid leftover highlights

package.json, src/config.ts, src/cursor_manager.ts
new settings
- `vscode-neovim.normalSelectionDebounceTime`
- `vscode-neovim.mouseSelectionDebounceTime`
Resolve: #1475
=> feat: add options to disable or change selection debounce time

src/cursor_manager.ts, src/test/suite/vscode-integration-specific.test.ts
=> fix(cursor): avoid unnecessary selections updates

runtime/lua/vscode-neovim/cursor.lua
=> fix(visual): clear fake cursor correctly

README.md
Close #1056, close #1145, close #97
=> docs: Introduce `vscode-multi-cursor.nvim`

package.json, src/highlight_provider.ts
chore(schema): predefine highlight `CurSearch`
=> fix(highlight): make `borderColor` work

src/buffer_manager.ts, src/test/suite/vscode-integration-specific.test.ts
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1577
=> fix: Cancel visual mode when switching editor

runtime/lua/vscode-neovim/internal.lua, src/commands_controller.ts, src/document_change_manager.ts, src/eventBus.ts, src/test/suite/dot-repeat.test.ts, src/utils.ts
- Resolve #1580
- Refactor using lua: 
- More concise
- Faster
- Might have alleviated #1534 as it's faster now
=> fix(dotrepeat): incorrect order of deletion and addition

runtime/lua/vscode-neovim/cursor.lua, src/cursor_manager.ts, src/test/suite/visual-modes.test.ts
Rework "viw" on last symbol
Discovered this minor issue while debugging the tests of the previous PR and thought of this idea. So far, it seems to be working fine.
=> fix(visual): optimized simulation of VisualChanged event

README.md, src/cursor_manager.ts, src/eventBus.ts, src/main_controller.ts, vim/vscode-neovim.vim
Remove vim functions implementation and internally call Lua function for backward compatibility.
=> refactor(api): call Lua API within vim functions

README.md
Problem:
- Not easy to ctrl-f in the readme to find how to migrate from the old Vimscript api.
- Readme still mentions Vimscript first and is too verbose.
- Repetitive, verbose explanations of api.
Solution:
- Move the Vimscript section to the bottom.
- Condense it and list the alternative Lua api for each case.
- Don't repeat the parameter descriptions for `vscode.call`. Link to the description for `vscode.action`.
=> docs: emphasize and clarify Lua api

src/document_change_manager.ts, src/test/suite/basic-editing-navigation.test.ts
=> fix(document_change): eol is inconsistent when processing changes

package.json, src/extension.ts, src/main_controller.ts
improve: Make vscode-neovim.stop can be executed multiple times
1. Customizing the when context to make keybindings more flexible.
2. Executing multiple commands.
3. ...
=> feat: Add command "vscode-neovim.lua"

runtime/lua/vscode-neovim/api.lua, runtime/lua/vscode-neovim/cursor.lua, src/test/suite/visual-modes.test.ts
=> fix: Cannot use strwidth to get string length

README.md
=> docs: Improve the section on disabling keybindings

runtime/lua/vscode-neovim/internal.lua, runtime/lua/vscode-neovim/util.lua, src/cursor_manager.ts
=> fix(visual): Fix syncing vscode selection to nvim

src/buffer_manager.ts
Remove buffers for disposed editors before creating new buffers to avoid naming conflicts.
Fixes https://github.com/vscode-neovim/vscode-neovim/issues/1651
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/f8188db1-2e18-4eab-9422-21c6a02a7fba
https://github.com/vscode-neovim/vscode-neovim/assets/16840190/3bef4d45-a0fa-4b5e-a9bd-bfce1b606c9f
=> fix(buffer): bufname conflict when creating a new buffer

runtime/lua/vscode-neovim/sync-options.lua, src/buffer_manager.ts, src/main_controller.ts
Please see the commits for details
=> refactor: refactor buffer manager

package-lock.json, package.json
Something has changed since VS Code 1.85.0
=> fix(test): upgrade @vscode/test-electron

src/main_controller.ts
=> fix: set correct cwd for WSL

package.json, src/config.ts, src/main_controller.ts
=> feat: Allow specifying WSL distro by wslDistribution

runtime/lua/vscode-neovim/internal.lua, src/buffer_manager.ts, src/eventBus.ts, src/main_controller.ts, src/utils.ts, vim/vscode-neovim.vim
=> fix(buffer): prefer real path as buffer name

src/extension.ts, src/main_controller.ts
Fixes #1702
Give more love to new vscode-neovim users from vscode who have never used nvim before.
=> fix: auto stop extension when starting nvim failed

.vscode/settings.json, README.md, package.json, scripts/keybindings/5_widgets.cjs, src/extension.ts, src/main_controller.ts
Please see the commits for details
=> chore: some minor optimizations

package.json, scripts/keybindings/5_widgets.cjs, scripts/keybindings/6_vscode_integration.cjs
=> fix: C-w in cmdline

package.json, scripts/keybindings/5_widgets.cjs
=> feat: handle C-d/C-u in hover widget

README.md, package-lock.json, package.json, src/buffer_manager.ts, src/commands_controller.ts, src/cursor_manager.ts
replaces https://github.com/vscode-neovim/vscode-neovim/pull/1783
=> build(deps-dev): bump prettier from 3.0.3 to 3.2.5

.github/dependabot.yml
~~Also change PR prefix to `deps:`.~~
=> chore: manage GitHub Actions with dependabot

src/main_controller.ts
ref https://github.com/vscode-neovim/vscode-neovim/issues/1756#issuecomment-1932208619
ref https://github.com/vscode-neovim/vscode-neovim/issues/1776#issuecomment-1934283115
Example output:
```
2024-02-14 00:19:12.593 [info] MainController: starting nvim: /usr/local/bin/nvim -N --embed --cmd source /Users/x/vscode-neovim/vim/vscode-neovim.vim -S /Users/x/vscode-neovim/runtime/lua/vscode-neovim/force-options.lua -c cd /Users/x/nvim-lspconfig
2024-02-14 00:19:12.741 [info] MainController: Nvim info:  {
logFile: '/Users/x/.local/state/nvim/log',
configDir: '/Users/x/.config/nvim',
configFile: '/Users/x/.config/nvim/init.vim',
nvimVersion: {
minor: 10,
api_compatible: 0,
api_level: 12,
major: 0,
patch: 0,
prerelease: true,
api_prerelease: true,
build: 'g32b49448b227'
}
}
```
=> feat(logging): log Nvim info at startup

src/main_controller.ts
Problem:
On macOS and possibly other systems, folders like `~/Downloads` may be inaccessible even though the fullpath to `nvim` located in that folder is executable. This will result in Lua errors.
Solution:
Show an error if VSCode cannot read `$VIMRUNTIME`.
Fix #1815
P.S. I have a followup PR that will add tests for logging and startup.
=> feat(logging): check that $VIMRUNTIME is readable

.eslintrc.js, src/command_line_manager.ts, src/commands_controller.ts, src/document_change_manager.ts, src/typing_manager.ts, tsconfig.json
=> build: enable "noUnusedLocals"

package.json
=> chore: consistent command titles

src/constants.ts, src/main_controller.ts, vim/vscode-neovim.vim
=> feat: Auto find a suitable neovim executable

runtime/lua/vscode-neovim/highlight.lua
fix #1739
fix #1767 Not 100% sure
=> fix(highlight): timely win hl ns setup, disable treesitter highlighting

src/cursor_manager.ts
=> fix(cursor): always reveal the nvim cursor position

src/highlights/highlight_grid.ts, src/test/unit/highlights/highlight_grid.test.ts
Just a small refactor :) It also cleans up one of the tests that I felt was a bit weird, but AFAICT has no impact on functionality
=> refactor: simplify highlight range building logic

README.md
=> docs: Add remote development section

package.json, src/typing_manager.ts
Ref Issue: #1922
Ref: https://stackoverflow.com/questions/3203190/regex-any-ascii-character
=> fix: Match any ASCII characters in composite keys

src/test/integ/yanking.test.ts
=> test: rework vi{ test

.github/workflows/build_test.yml
GabrielBB/xvfb-action is deprecated.
=> ci: replace GabrielBB/xvfb-action with coactions/setup-xvfb

README.md, runtime/modules/ui.lua, src/actions_eval.ts, src/test/integ/actions.test.ts
some small changes to match the changes introduced in https://github.com/vscode-neovim/vscode-neovim/pull/1966
- README updated
- added a few test cases
- removed redundant use of JSON.stringify
=> chore: update eval docs and tests

src/cmdline/cmdline_controller.ts
=> fix: wildmenu items are being set repeatedly

CONTRIBUTING.md
Re: https://github.com/vscode-neovim/vscode-neovim/pull/1962#issuecomment-2121150601
=> docs: indicate you can view logs in the Debug Console

runtime/vscode/statusline.lua, src/eventBus.ts, src/status_line_manager.ts
=> fix: pulling status causes a redraw

src/cursor_manager.ts, src/document_change_manager.ts, src/test/integ/insert-mode.test.ts, src/typing_manager.ts
=> fix: update expected cursor when multiple docs change

src/document_change_manager.ts, src/test/integ/basic-editing-navigation.test.ts
- fix #2023
- fix #1624 (Maybe)
=> fix: Correctly set doc version for skipping changes

runtime/vscode/overrides/vscode-file-commands.vim, src/buffer_manager.ts, src/test/integ/vscode-integration-specific.test.ts
Reverts vscode-neovim/vscode-neovim#2027
=> Revert "refactor: remove Altercmd for "write""

src/extension.ts, src/logger.ts, src/main_controller.ts, src/messages_manager.ts
- Init log output channel in logger
- Init message output channel in message manager
=> refactor: init output channels in the corresponding manager

README.md, runtime/vscode/lsp/buf.lua
=> feat: override vim.lsp.buf methods

src/main_controller.ts
fix #2077
nvim may in the different fs
=> fix: set current dir in nvim

package.json, scripts/keybindings/5_widgets.cjs
- ctrl+n => focusNextRenameSuggestion
- ctrl+p => focusPreviousRenameSuggestion
=> feat: ctrl+n/ctrl+p for selecting rename suggestions

runtime/lua/vscode/api.lua, runtime/vscode-neovim.vim
=> fix: adapt to Nvim deprecations in 0.10

runtime/lua/vscode/default-options.lua, runtime/lua/vscode/force-options.lua, src/main_controller.ts, src/messages_manager.ts
=> fix: Align output with nvim messages and auto show based on cmdheight

src/buffer_manager.ts, src/document_change_manager.ts, src/utils/vscode.ts
Primarily for debugging purposes, a potential issue was discovered in https://github.com/vscode-neovim/vscode-neovim/issues/2131#issuecomment-2198828483, but it's not confirmed. Adding a progress bar will not impact user experience, and if there is an issue, it will be easier to identify.
=> feat: Add progress indicator for layout sync

runtime/lua/vscode/highlight.lua
=> fix(highlight): Fix pattern matching of syntax groups

package.json
=> refactor: Remove debounce time limit for sync mouse selection

README.md
Inform users to find all available settings and commands in the Features tab of the extension details.
=> docs: Add settings and commands section

src/actions.ts, src/cursor_manager.ts, src/utils/vscode.ts
=> fix: Cancel UI-affecting tasks upon disposal

runtime/lua/vscode/internal.lua, runtime/vscode/filetype.lua, src/buffer_manager.ts
=> fix: manually set languageId to buffer filetype for special documents

src/highlight_manager.ts
=> fix(highlight): leading dashes could be combined with statuscolumn

src/cursor_manager.ts
=> fix(cursor): compare active position, not selection

runtime/vscode-neovim.vim
=> fix(startup): unclear "minimum version" message for nvim prerelease

CONTRIBUTING.md, README.md
Docs are not clear about how to set debug logging.
=> docs: how to configure Debug logging

src/test/integ/highlights.test.ts
=> test: failing "highlights forward search / for long line"

README.md
Small PR - Commit 3a5ecb26086ca9f4add610e8d6844e1762e9d122 moved `code_actions.lua`. This PR adjusts sources to changes. It also fixes a typo along the way.
=> chore: update `code_actions.lua` reference

README.md
=> docs: vscode docs for the "when" clause

src/utils/vscode.ts
=> fix: replace execSync with spawnSync

runtime/vscode/treesitter.lua
https://github.com/vscode-neovim/vscode-neovim/pull/2356#issuecomment-2684120268
=> fix: we need to execute treesitter parsing manually

src/buffer_manager.ts
=> fix: improve window change handling with cancellation support

runtime/lua/vscode/api.lua, src/test/integ/lua-with-insert.test.ts
=> fix(api): add delay for cursor synchronization in with_insert

src/buffer_manager.ts
Only send updates when the options we care about change.
=> perf: avoid unnecessary sending of editor options to neovim

README.md, runtime/lua/vscode/api.lua, src/actions.ts
=> fix(api): update configuration target options to include "workspace_folder"

src/cursor_manager.ts
=> fix: use the cursor style from VS Code as the style for insert mode

package.json
I'm not sure if this can completely solve the problem, but it seems to be a good workaround and has eliminated the problem on my local machine.
fix #2407
=> fix: do not open in copilot to fix #2407

package.json
Reverts vscode-neovim/vscode-neovim#2467
=> Revert "fix: do not open in copilot to fix #2407"

runtime/vscode/statusline.lua
=> fix: fallback statusline to empty

runtime/lua/vscode/default-options.lua, runtime/vscode/statusline.lua
PR #2518 did not resolve the issue.
=> fix: change the default statusline to an empty string
